export { EditorCore } from './core/EditorCore.js';
export type { EditorConfig, Command, FormatTag, TextAlign, ToolbarState, FormatName, MenuTab } from './core/types.js';
export { HistoryManager } from './core/history/HistoryManager.js';
export { Snapshot } from './core/history/Snapshot.js';
export { FormatCommand } from './core/commands/FormatCommand.js';
export { ClipboardHandler } from './modules/edit/ClipboardHandler.js';
export { FindReplace } from './modules/edit/FindReplace.js';
export { ImageEditor } from './modules/edit/ImageEditor.js';
export { ImageInserter, ALLOWED_IMG_EXTENSIONS } from './modules/insert/ImageInserter.js';
export { MultiImageUploader, MULTI_ALLOWED_EXTENSIONS } from './modules/insert/MultiImageUploader.js';
export { TableBuilder } from './modules/table/TableBuilder.js';
export { CellMerger, buildGridMap } from './modules/table/CellMerger.js';
export { TableNavigator } from './modules/table/TableNavigator.js';
export { TableResizer } from './modules/table/TableResizer.js';
export { TableSelector } from './modules/table/TableSelector.js';
export { TableHandle } from './modules/table/TableHandle.js';
export { TABLE_PRESETS, applyPreset } from './modules/table/TablePresets.js';
export type { TablePreset } from './modules/table/TablePresets.js';
export { TableContextMenu } from './modules/table/TableContextMenu.js';
export { PoaCellSplitDialog } from './components/dialogs/CellSplitDialog.js';
export type { TableOptions, HeaderPosition } from './modules/table/TableBuilder.js';
export type { GridCell, CellProperties, MergeResult } from './modules/table/CellMerger.js';
export type { TableNavigatorCallbacks } from './modules/table/TableNavigator.js';
export type { TableContextCallbacks } from './modules/table/TableContextMenu.js';
export type { FindOptions, FindState } from './modules/edit/FindReplace.js';
export type { CropRect, RotateDegrees, FlipDirection } from './modules/edit/ImageEditor.js';
export type { ImageAttributes, UploadConfig } from './modules/insert/ImageInserter.js';
export type { UploadItem, MultiUploadOptions, ValidationResult } from './modules/insert/MultiImageUploader.js';

import { PoaMenuBar } from './components/MenuBar.js';
import { PoaContextToolbar } from './components/ContextToolbar.js';
import { PoaToolbar } from './components/Toolbar.js';
import { PoaEditor } from './components/PoaEditor.js';
import { PoaStatusBar } from './components/StatusBar.js';
import { PoaSettingsDialog } from './components/dialogs/SettingsDialog.js';
import { PoaFindReplaceDialog } from './components/dialogs/FindReplaceDialog.js';
import { PoaImageEditDialog } from './components/dialogs/ImageEditDialog.js';
import { PoaImageDialog } from './components/dialogs/ImageDialog.js';
import { PoaTableDialog } from './components/dialogs/TableDialog.js';
import { PoaCellSplitDialog } from './components/dialogs/CellSplitDialog.js';

// poa-editor의 connectedCallback 시점에 모든 하위 요소가 이미 정의되어 있어야 한다.
// poa-editor를 마지막으로 등록하면 shadow.innerHTML 파싱 시 child 요소가 즉시 업그레이드된다.
if (!customElements.get('poa-menubar'))              customElements.define('poa-menubar',              PoaMenuBar);
if (!customElements.get('poa-context-toolbar'))      customElements.define('poa-context-toolbar',      PoaContextToolbar);
if (!customElements.get('poa-toolbar'))              customElements.define('poa-toolbar',              PoaToolbar);
if (!customElements.get('poa-status-bar'))           customElements.define('poa-status-bar',           PoaStatusBar);
if (!customElements.get('poa-settings-dialog'))      customElements.define('poa-settings-dialog',      PoaSettingsDialog);
if (!customElements.get('poa-find-replace-dialog'))  customElements.define('poa-find-replace-dialog',  PoaFindReplaceDialog);
if (!customElements.get('poa-image-edit-dialog'))    customElements.define('poa-image-edit-dialog',    PoaImageEditDialog);
if (!customElements.get('poa-image-dialog'))         customElements.define('poa-image-dialog',         PoaImageDialog);
if (!customElements.get('poa-table-dialog'))         customElements.define('poa-table-dialog',         PoaTableDialog);
if (!customElements.get('poa-cell-split-dialog'))    customElements.define('poa-cell-split-dialog',    PoaCellSplitDialog);
if (!customElements.get('poa-editor'))               customElements.define('poa-editor',               PoaEditor);
